from seleniumbase import BaseCase
BaseCase.main(__name__, __file__)
from dotenv import load_dotenv
import os

load_dotenv(dotenv_path= ".env")
# mainbaseUrl = os.getenv("mainbaseUrl")
mainbaseUrl = "https://dev-main-master1.vedant.life"


class Testcases(BaseCase):
    def test_gitaenquiry(self):
        self.open(mainbaseUrl)
        self.click("div#main-website-nav-item-in-place-live span")
        self.click("div#main-website-nav-item-in-place-live div:nth-of-type(2) span")
        self.click("div#svelte div:nth-of-type(2) div:nth-of-type(2) div div:nth-of-type(4) div:nth-of-type(3) button")
        self.type("input#form-field-name", "Logout Gita Enquiry")
        self.type("input#form-field-email", "enq1@g.cc")
        self.click("input#form-field-phone")
        self.type("input#form-field-phone", "1895461230")
        self.type("input#form-field-age", "20")
        self.select_option_by_text("select#form-field-gender", "Male")
        self.select_option_by_text("select#form-field-listening-time", "Less than a month")
        # self.select_option_by_text("select#form-field-profession", "Construction or Real Estate")
        self.select_option_by_text("select#form-field-profession", "Student")
        self.select_option_by_text("select#form-field-state", "Haryana")
        self.click("div#form-field-search-city")
        self.click('span:contains("Bahadurgarh")')
        self.check_if_unchecked("input#form-field-disclaimer")
        self.click("div#svelte > div:nth-of-type(2) > div:nth-of-type(2) > div:nth-of-type(5) > div > div:nth-of-type(3) > div")
    
    def test_vbcenroll(self):
        self.open(mainbaseUrl)
        self.click("div#main-website-nav-item-in-place-live span")
        self.click("div#main-website-nav-item-in-place-live div:nth-of-type(2) div:nth-of-type(2)")
        self.click("div#svelte div:nth-of-type(2) div:nth-of-type(2) div div:nth-of-type(4) div:nth-of-type(2) div:nth-of-type(4) button")
        self.type("input#form-field-name", "Logout VBC Enquiry")
        self.type("input#form-field-email", "enq2@g.cc")
        self.click("div#svelte > div:nth-of-type(2) > div:nth-of-type(2) > div:nth-of-type(5) > div > div > div > div:nth-of-type(3)")
        self.type("input#form-field-phone", "1312369870")
        self.type("input#form-field-age", "20")
        self.select_option_by_text("select#form-field-gender", "Male")
        self.select_option_by_text("select#form-field-listening-time", "Less than a month")
        self.select_option_by_text("select#form-field-profession", "Student")
        self.select_option_by_text("select#form-field-state", "Jammu and Kashmir")
        self.check_if_unchecked("input#form-field-disclaimer")
        self.click("div#svelte > div:nth-of-type(2) > div:nth-of-type(2) > div:nth-of-type(5) > div > div:nth-of-type(3) > div")
    
    def test_Login_gita_enquiry(self):
        self.open(mainbaseUrl)
        self.click("div#main-website-right-menu-btn div")
        # self.click('a[href="/en/login?page=https%3A%2F%2Fdev-main-master2.vedant.life%2F"] svg path')
        self.click_link_text("Login")
        self.click('button:contains("Sign In with Email")')
        self.type("input#main-website-input-username", "enq3@g.cc")
        self.type("input#password", "enq3@g.cc")
        self.click("button#main-website-sign-in-btn")
        self.click("div#main-website-nav-item-in-place-live")
        self.click("div#main-website-nav-item-in-place-live div:nth-of-type(2) span")
        self.click("div#svelte div:nth-of-type(2) div:nth-of-type(2) div div:nth-of-type(4) div:nth-of-type(3) button")
        self.type("input#form-field-name", "Login Gita Enquiry")
        self.type("input#form-field-phone", "1196352401")
        self.type("input#form-field-age", "20")
        self.select_option_by_text("select#form-field-gender", "Male")
        self.select_option_by_text("select#form-field-listening-time", "Less than a month")
        # self.select_option_by_text("select#form-field-profession", "Video or Photo-Editing")
        self.select_option_by_text("select#form-field-profession", "Student")
        self.select_option_by_text("select#form-field-state", "Haryana")
        self.click("div#form-field-search-city div")
        self.click('span:contains("Bahadurgarh")')
        self.check_if_unchecked("input#form-field-disclaimer")
        self.click("div#svelte > div:nth-of-type(2) > div:nth-of-type(2) > div:nth-of-type(5) > div > div:nth-of-type(3) > div")
    
    def test_login_vbc_enquiry(self):
        self.open(mainbaseUrl)
        self.click("div#main-website-right-menu-btn div")
        # self.click('a[href="/en/login?page=https%3A%2F%2Fdev-main-master2.vedant.life%2F"] svg path')
        self.click_link_text("Login")
        self.click('button:contains("Sign In with Email")')
        self.type("input#main-website-input-username", "enq4@g.cc")
        self.type("input#password", "enq4@g.cc")
        self.click("button#main-website-sign-in-btn")
        self.click("div#main-website-nav-item-in-place-live span")
        self.click("div#main-website-nav-item-in-place-live div:nth-of-type(2) div:nth-of-type(2) span")
        self.click("div#svelte div:nth-of-type(2) div:nth-of-type(2) div div:nth-of-type(4) div:nth-of-type(2) div:nth-of-type(4) button")
        self.type("input#form-field-name", "Login VBC Enquiry")
        self.type("input#form-field-phone", "1096352401") 
        self.type("input#form-field-age", "20")
        self.select_option_by_text("select#form-field-gender", "Male")
        # self.select_option_by_text("select#form-field-listening-time", "1 to 6 months")
        self.select_option_by_text("select#form-field-listening-time", "Less than a month")
        # self.select_option_by_text("select#form-field-profession", "Construction or Real Estate")
        self.select_option_by_text("select#form-field-profession", "Student")
        self.select_option_by_text("select#form-field-state", "Jammu and Kashmir")
        self.check_if_unchecked("input#form-field-disclaimer")
        self.click('span:contains("Submit")')
